// Generated by CoffeeScript 1.3.3
(function() {
  var Circulator;

  Circulator = (function() {

    function Circulator(Maschine) {
      this.Maschine = Maschine;
    }

    Circulator.prototype.circulate = function() {
      return this.Maschine.circulate();
    };

    return Circulator;

  })();

  window.Circulator = Circulator;

}).call(this);
