// Generated by CoffeeScript 1.3.3
(function() {
  var Circulator;

  Circulator = (function() {

    function Circulator(Method) {
      this.Method = Method;
      this.prototype.circulate = Method;
    }

    return Circulator;

  })();

  window.Circulator = Circulator;

}).call(this);
