// Generated by CoffeeScript 1.3.3
(function() {
  var TestMaschine, testMaschine,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TestMaschine = (function(_super) {

    __extends(TestMaschine, _super);

    function TestMaschine(canvasName, width, height) {
      this.ev_mouse = __bind(this.ev_mouse, this);

      this.ev_keydown = __bind(this.ev_keydown, this);

      var centerX, centerY;
      TestMaschine.__super__.constructor.call(this, canvasName, width, height);
      centerX = Math.floor(this.dimX / 2);
      centerY = Math.floor(this.dimY / 2);
      this.fadenkreuz = new Point(centerX, centerY);
      this.l1 = new Line("#000000", new Point(0, 0), this.fadenkreuz);
      this.l2 = new Line("#000000", new Point(this.dimX, 0), this.fadenkreuz);
      this.l3 = new Line("#000000", new Point(this.dimX, this.dimY), this.fadenkreuz);
      this.l4 = new Line("#000000", new Point(0, this.dimY), this.fadenkreuz);
      this.rec_l = new Point(100, 100);
      this.rec_r = new Point(300, 100);
      this.rec_u = new Point(200, 200);
      this.l5 = new Line("#000000", this.rec_l, this.fadenkreuz);
      this.l6 = new Line("#000000", this.rec_r, this.fadenkreuz);
      this.l7 = new Line("#000000", this.rec_u, this.fadenkreuz);
      this.poly = new Polygon("#000000", [this.rec_l, this.rec_r, this.rec_u]);
      this.polly = new Polygon("#00AA00", [this.rec_l, this.rec_r, this.fadenkreuz]);
      this.addObjectShyly(this.l1);
      this.addObjectShyly(this.l2);
      this.addObjectShyly(this.l3);
      this.addObjectShyly(this.l4);
      this.addObjectShyly(this.l5);
      this.addObjectShyly(this.l6);
      this.addObjectShyly(this.l7);
      this.addObjectShyly(this.poly);
      this.addObject(this.polly);
    }

    TestMaschine.prototype.ev_keydown = function(event) {
      var speed;
      speed = 4;
      if (event.keyCode === 37) {
        this.poly.move(-speed, 0);
      } else if (event.keyCode === 38) {
        this.poly.move(0, -speed);
      } else if (event.keyCode === 39) {
        this.poly.move(speed, 0);
      } else if (event.keyCode === 40) {
        this.poly.move(0, speed);
      }
      return this._refresh();
    };

    TestMaschine.prototype.ev_mouse = function(event) {
      this.l1.setTo(event.clientX, event.clientY);
      this.l2.setTo(event.clientX, event.clientY);
      this.l3.setTo(event.clientX, event.clientY);
      this.l4.setTo(event.clientX, event.clientY);
      this.l5.setTo(event.clientX, event.clientY);
      this.l6.setTo(event.clientX, event.clientY);
      this.l7.setTo(event.clientX, event.clientY);
      this.polly.getPoint(2).moveTo(event.clientX, event.clientY);
      return this._refresh();
    };

    return TestMaschine;

  })(Maschine);

  testMaschine = new TestMaschine("canvasArea", window.innerWidth - 20, window.innerHeight - 20);

  document.documentElement.style.overflow = 'hidden';

}).call(this);
