// Generated by CoffeeScript 1.3.3
(function() {
  var color, i, testMaschine, tmp, x1, x2, y1, y2, _i;

  testMaschine = new Maschine("canvasArea", 400, 300);

  for (i = _i = 0; _i <= 4; i = ++_i) {
    color = "#000000";
    x1 = Math.random() * testMaschine.dimX;
    x2 = (x1 + Math.random() * testMaschine.dimX) % testMaschine.dimX;
    y1 = Math.random() * testMaschine.dimY;
    y2 = (y1 + Math.random() * testMaschine.dimY) % testMaschine.dimY;
    tmp = new Rectangle(color, x1, y1, x2, y2);
    testMaschine.registerNewObject(tmp);
  }

}).call(this);
