// Generated by CoffeeScript 1.3.3
(function() {
  var maschine, newID;

  maschine = (function() {
    var name, objects;

    objects = [];

    name = "";

    function maschine(sectionID, dimX, dimY) {
      var sect;
      this.sectionID = sectionID;
      this.dimX = dimX;
      this.dimY = dimY;
      name = newID();
      sect = document.getElementById(this.sectionID);
      sect.innerHTML = "<canvas id=" + this.name + " width=" + this.dimX + " height=" + this.dimY;
    }

    maschine.prototype.registerNewObject = function() {};

    maschine.prototype.removeObject = function() {};

    maschine.prototype.updateObject = function() {};

    maschine.prototype.userInput = function() {};

    return maschine;

  })();

  newID = function() {
    return Math.random() * 16;
  };

}).call(this);
