// Generated by CoffeeScript 1.3.3
(function() {
  var maschine;

  maschine = (function() {
    var objects;

    objects = [];

    function maschine(sectionID) {
      this.sectionID = sectionID;
    }

    maschine.prototype.registerNewObject = function() {};

    maschine.prototype.removeObject = function() {};

    maschine.prototype.updateObject = function() {};

    maschine.prototype.userInput = function() {};

    return maschine;

  })();

}).call(this);
