// Generated by CoffeeScript 1.3.3
(function() {
  var RandMaschine, testMaschine,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RandMaschine = (function(_super) {

    __extends(RandMaschine, _super);

    function RandMaschine() {
      this.ev_mouse = __bind(this.ev_mouse, this);
      return RandMaschine.__super__.constructor.apply(this, arguments);
    }

    RandMaschine.prototype.ev_mouse = function(event) {
      var color, i, tmp, x1, x2, y1, y2, _i, _results;
      _results = [];
      for (i = _i = 0; _i <= 4; i = ++_i) {
        color = "#000000";
        x1 = Math.floor(Math.random() * testMaschine.dimX);
        x2 = Math.floor((x1 + Math.random() * testMaschine.dimX) % testMaschine.dimX);
        y1 = Math.floor(Math.random() * testMaschine.dimY);
        y2 = Math.floor((y1 + Math.random() * testMaschine.dimY) % testMaschine.dimY);
        tmp = new Rectangle(color, x1, y1, x2, y2);
        this.clear();
        _results.push(this.addObject(tmp));
      }
      return _results;
    };

    return RandMaschine;

  })(Maschine);

  testMaschine = new RandMaschine("canvasArea", 800, 600);

}).call(this);
