// Generated by CoffeeScript 1.3.3
(function() {
  var TestMaschine, testMaschine,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TestMaschine = (function(_super) {

    __extends(TestMaschine, _super);

    function TestMaschine(canvasName, width, height) {
      this.ev_mouse = __bind(this.ev_mouse, this);

      var centerX, centerY;
      TestMaschine.__super__.constructor.call(this, canvasName, width, height);
      centerX = Math.floor(this.dimX / 2);
      centerY = Math.floor(this.dimY / 2);
      this.l1 = new Line("#000000", new Point(0, 0), new Point(centerX, centerY));
      this.l2 = new Line("#000000", new Point(this.dimX, 0), new Point(centerX, centerY));
      this.l3 = new Line("#000000", new Point(this.dimX, this.dimY), new Point(centerX, centerY));
      this.l4 = new Line("#000000", new Point(0, this.dimY), new Point(centerX, centerY));
      this.addObjectShyly(this.l1);
      this.addObjectShyly(this.l2);
      this.addObjectShyly(this.l3);
      this.addObject(this.l4);
    }

    TestMaschine.prototype.ev_mouse = function(event) {
      this.l1.toX = event.clientX;
      this.l1.toY = event.clientY;
      this.l2.toX = event.clientX;
      this.l2.toY = event.clientY;
      this.l3.toX = event.clientX;
      this.l3.toY = event.clientY;
      this.l4.toX = event.clientX;
      this.l4.toY = event.clientY;
      return this._refresh();
    };

    return TestMaschine;

  })(Maschine);

  testMaschine = new TestMaschine("canvasArea", window.innerWidth - 20, window.innerHeight - 20);

}).call(this);
