// Generated by CoffeeScript 1.3.3
(function() {
  var Bla, blubb;

  Bla = (function() {

    function Bla(name) {
      this.name = name;
    }

    Bla.prototype.blubb = function() {
      return alert(this.name);
    };

    return Bla;

  })();

  blubb = new Bla("hollereidullioe");

  blubb.blubb();

  Bla.prototype.blubb = function() {
    return alert("modified" + this.name);
  };

  blubb.blubb();

}).call(this);
