// Generated by CoffeeScript 1.3.3
(function() {
  var getRandomColor;

  getRandomColor = function() {
    var color, i, letters, _i;
    letters = '0123456789ABDCEF'.split('');
    color = '#';
    for (i = _i = 0; _i <= 5; i = ++_i) {
      color += letters[Math.round(Math.random() * 15)];
    }
    return color;
  };

  window.getRandomColor = getRandomColor;

}).call(this);
