// Generated by CoffeeScript 1.3.3
(function() {
  var KlickPolygon, klick,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  KlickPolygon = (function(_super) {

    __extends(KlickPolygon, _super);

    function KlickPolygon(secId) {
      this.ev_click = __bind(this.ev_click, this);
      KlickPolygon.__super__.constructor.call(this, secId, window.innerWidth - 20, window.innerHeight - 20);
      this.objects.push(new Polygon("#000000", [new Point(100, 100)]));
      this.counter = 0;
    }

    KlickPolygon.prototype.ev_click = function(event) {
      var x, y;
      x = event.clientX;
      y = event.clientY;
      if (event.button === 0) {
        return this.objects[this.counter].points.push(new Point(x, y));
      } else if (event.button === 1) {
        this.counter += 1;
        return this.objects.push(new Polygon(getRandomColor(), [new Point(x, y)]));
      }
    };

    return KlickPolygon;

  })(Maschine);

  klick = new KlickPolygon("canvasArea");

}).call(this);
