// Generated by CoffeeScript 1.3.3
(function() {
  var RandMaschine, getRandomColor, testMaschine,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RandMaschine = (function(_super) {

    __extends(RandMaschine, _super);

    function RandMaschine() {
      this.ev_keydown = __bind(this.ev_keydown, this);

      this.ev_mouse = __bind(this.ev_mouse, this);
      return RandMaschine.__super__.constructor.apply(this, arguments);
    }

    RandMaschine.prototype.ev_mouse = function(event) {
      var color, i, tmp, x1, x2, y1, y2, _i, _results;
      this.clear();
      _results = [];
      for (i = _i = 0; _i <= 10; i = ++_i) {
        color = "#000000";
        x1 = Math.floor(Math.random() * testMaschine.dimX * 1.5) - testMaschine.dimX / 4;
        x2 = Math.ceil(Math.random() * testMaschine.dimX) + testMaschine.dimX / 4;
        y1 = Math.floor(Math.random() * testMaschine.dimY) - testMaschine.dimY / 4;
        y2 = Math.ceil(Math.random() * testMaschine.dimY) + testMaschine.dimY / 4;
        tmp = new Rectangle(color, x1, y1, x2, y2);
        _results.push(this.addObject(tmp));
      }
      return _results;
    };

    RandMaschine.prototype.ev_keydown = function(event) {
      var o, _i, _len, _ref;
      _ref = this.objects;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        o = _ref[_i];
        o.color = getRandomColor();
      }
      return this._refresh();
    };

    return RandMaschine;

  })(Maschine);

  getRandomColor = function() {
    var color, i, letters, _i;
    letters = '0123456789ABDCEF'.split('');
    color = '#';
    for (i = _i = 0; _i <= 5; i = ++_i) {
      color += letters[Math.round(Math.random() * 15)];
    }
    return color;
  };

  testMaschine = new RandMaschine("canvasArea", window.innerWidth - 20, window.innerHeight - 20);

  document.documentElement.style.overflow = 'hidden';

  document.body.scroll = "no";

}).call(this);
